# Generated by Django 6.0.6 on 2026-08-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='empId',
            field=models.CharField(default='cst899', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='xenzi', max_length=30),
        ),
    ]
