# Generated by Django 6.0.6 on 2026-08-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_empid_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mail',
            field=models.EmailField(default=None, max_length=50, unique=True),
        ),
    ]
