# Generated by Django 6.0.6 on 2026-08-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mail',
            field=models.EmailField(default='peddamallanavadeep@gmail.com', max_length=50, unique=True),
        ),
    ]
