# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_empid_alter_userprofile_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='empId',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
